version: '3.1'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart : unless-stopped
    networks:
      - backend
  express:
    container_name: express
    image: ream123/aiez-server:latest
    environment:
      - DB_HOST=root
      - DB_PASSWOD=password
      - MONGO_URL=mongo:27017/aiez
      - COOKIE_SECRET=kJ`+=Mj3t}<*8A6fuW{z9}z16iqxC3
    expose:
      - "4000"
    networks:
      - backend
    depends_on:
      - mongo
    restart : unless-stopped
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volume:/data/db
    networks:
      - backend
    restart : unless-stopped
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8090:8090
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - backend
networks:
  backend:
    driver: bridge
